// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"

	profile "github.com/jariwat/p_project/profile-service/service/profile"

	uuid "github.com/google/uuid"
)

// ServerInterface is an autogenerated mock type for the ServerInterface type
type ServerInterface struct {
	mock.Mock
}

// DeleteProfileId provides a mock function with given fields: c, id
func (_m *ServerInterface) DeleteProfileId(c *gin.Context, id uuid.UUID) {
	_m.Called(c, id)
}

// GetProfileId provides a mock function with given fields: c, id
func (_m *ServerInterface) GetProfileId(c *gin.Context, id uuid.UUID) {
	_m.Called(c, id)
}

// GetProfiles provides a mock function with given fields: c, params
func (_m *ServerInterface) GetProfiles(c *gin.Context, params profile.GetProfilesParams) {
	_m.Called(c, params)
}

// PostProfile provides a mock function with given fields: c
func (_m *ServerInterface) PostProfile(c *gin.Context) {
	_m.Called(c)
}

// PutProfileId provides a mock function with given fields: c, id
func (_m *ServerInterface) PutProfileId(c *gin.Context, id uuid.UUID) {
	_m.Called(c, id)
}

// NewServerInterface creates a new instance of ServerInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewServerInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *ServerInterface {
	mock := &ServerInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
